In [5]:
import numpy as np
mylist=[1,2,3,4]
arr=np.array(mylist)# np changes list into array
arr

list2=[[1,2,3],[4,5,6],[7,8,6]]
np.array(list2)#NP CONVERTS LIST INTO 3 DIMENTIIONAL ARRAY
list2[0][0] # FINDS OUT THE FIRST VALUE OF FIRST ELEMENT IN LIST LIKE MATRICX... 00,01,02,03,10,12,13,....

1

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)#jumping 2 steps each time

array([0, 2, 4, 6, 8])

In [10]:
np.zeros((2,3)) #making a metricx of 2 row and 3 column

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.linspace(0,5,10)# here 10 is the number of points starts countiong from 0 and will have 5 columns

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.random.rand(5)

array([0.03586933, 0.66657837, 0.03516615, 0.8592392 , 0.94706431])

In [17]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
np.random.randint(0,5,10)#take 0 to 5 and print them 10 times

array([2, 3, 1, 4, 2, 4, 3, 1, 3, 0])

In [29]:
arry=np.arange(25)
arry.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arry.max()

24

In [32]:
arry.min()

0

In [109]:
# arry=np.random.randint(0,25,4)#take 0 to 5 and print them 10 times
# print(arry)
arry.argmax()#shoes the position of max value

[ 2 14 20 14]


2

In [111]:
arry.shape

(4,)

In [112]:
arr.dtype

dtype('int64')

In [114]:
from numpy.random import randint

In [184]:
randint(2,10)

2

In [186]:
arr[0:6]

array([1, 2, 3, 4])

In [193]:
arr[3:6]=3
arr

array([3, 3, 3, 3])

In [195]:
#arr of 10 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
np.arange(10,51)#10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [198]:
np.arange(10,51,2)#stepsize 2 gives all the even numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [200]:
np.arange(9).reshape(3,3) #making a 3by 3 matrix from the value 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [203]:
np.random.rand(25)

array([0.45827767, 0.81724464, 0.90126655, 0.94592488, 0.22003002,
       0.13702311, 0.45088228, 0.47608216, 0.68746083, 0.39509156,
       0.32105951, 0.22748246, 0.34708077, 0.14558502, 0.9830927 ,
       0.34565698, 0.41525589, 0.88506306, 0.6426288 , 0.44677407,
       0.65688496, 0.19620509, 0.2287755 , 0.87016068, 0.64610624])

In [205]:
np.arange(1,101).reshape(10,10)/100# took 100 values made a 10 by 10 metrix and devide each value by 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [207]:
newarry=np.arange(1,101).reshape(10,10)/100
newarry[5:,:]#every thing grabbed after row 5

array([[0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [208]:
newarry[5:,6:] # every thing grabed after row 5 and column 6

array([[0.57, 0.58, 0.59, 0.6 ],
       [0.67, 0.68, 0.69, 0.7 ],
       [0.77, 0.78, 0.79, 0.8 ],
       [0.87, 0.88, 0.89, 0.9 ],
       [0.97, 0.98, 0.99, 1.  ]])

In [210]:
newarry.sum()

50.5

In [211]:
newarry.std()

0.2886607004772212

In [212]:
newarry.sum(axis=0)

array([4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])